### ISSUE TITLE
Provision Avogadro constant and Boltzmann constant kB

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-units#87]
Would it be better if the package could provide Avogadro constant and Boltzmann constant kB? With the correct unit.

The implementation could be as simple as

```
from scipy.constants import Avogadro, Boltzmann
from openff.units import unit as offunit
AVOGADRO_CONSTANT_NA = Avogadro / offunit.mole
BOLTZMANN_CONSTANT_kB = Boltzmann * offunit.joule / offunit.kelvin
```

**Comment by mattwthompson** [comment]
I don't want to add an extra dependency, I think I'll just yoink these lines from upstream: https://github.com/hgrecco/pint/blob/f2e4081aee38f850938048beac7fb69c4908bc5e/pint/constants_en.txt#L23-L24

What's missing from this registry isn't necessarily intentional, and adding stuff back in is relatively cheap

**Comment by mattwthompson** [comment]
Wait, they're already there. Is there something wrong with these units?

```python
In [1]: from openff.toolkit import unit

In [2]: (1 * unit.avogadro_constant).to(1 / unit.mole)
Out[2]: 6.02214076e+23 <Unit('1 / mole')>

In [3]: (1 * unit.boltzmann_constant).to(unit.kilojoule / unit.kelvin)
Out[3]: 1.3806490000000003e-26 <Unit('kilojoule / kelvin')>

**Comment by xiki-tempula** [comment]
This is great. I didn't know that.
